# These settings are synced to GitHub by https://probot.github.io/apps/settings/
repository:
  name: spock-outputcapture
  description: OutputCapture for the Spock Framework
  topics: spock-extension, spock-framework, output-checking
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  allow_update_branch: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
- name: waiting for feedback
  color: '#D4C5F9'
  description: Waiting for feedback issue/pr author
- name: dependencies
  color: '#0366d6'
  description: Pull requests that update a dependency file
- name: java
  color: '#ffa221'
  description: Pull requests that update Java code

branches:
- name: main
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    required_status_checks:
      strict: true
      checks:
      - context: build
        app_id: 15368
      - context: pre-commit.ci - pr
        app_id: 68672
      - context: Semantic Pull Request
        app_id: 9517
      - context: DCO
        app_id: 1861
    enforce_admins: false
    required_linear_history: true
    required_conversation_resolution: true
    restrictions:
