name: build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: zulu
    - name: build
      run: ./gradlew check
