name: build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - name: gradle setup
      uses: gradle/gradle-build-action@v2
    - name: build
      run: ./gradlew check
    - uses: codecov/codecov-action@v3
      with:
        files: spock-mockable/build/reports/jacoco/test/jacocoTestReport.xml
        flags: unit
    - uses: codecov/codecov-action@v3
      with:
        files: tests/build/reports/jacoco/test/jacocoTestReport.xml
        flags: integration
